//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SansPapier.Portail.Layouts.SansPapier.Portail {
    
    
    public partial class ActionsClient {
    }
}
