//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SansPapier.Portail.VisualWebParts.ProchainesSeancesWebPart {
    
    
    public partial class ProchainesSeancesUserControl {
        
        /// <summary>
        /// Titre_Section_Prochaines_Seances control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal Titre_Section_Prochaines_Seances;
        
        /// <summary>
        /// rptProchainesSeances control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptProchainesSeances;
    }
}
