//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SansPapier.Variation.Portail.VisualWebParts.ListeNouvelleWebPart {
    
    
    public partial class ListeNouvelleUserControl {
        
        /// <summary>
        /// rptNouvelles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Phoenix.UI.SharePoint.Controls.ListAggregator rptNouvelles;
        
        /// <summary>
        /// MessageAucuneNouvelle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label MessageAucuneNouvelle;
        
        /// <summary>
        /// lnkListeNouvelles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink lnkListeNouvelles;
    }
}
