//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SansPapier.Variation.Portail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SansPapier.Variation.Portail.Resources.global", typeof(global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions d&apos;utilisation.
        /// </summary>
        internal static string Conditions_Utilisation {
            get {
                return ResourceManager.GetString("Conditions_Utilisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2013 Agropur - .
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM yyyy.
        /// </summary>
        internal static string Format_date {
            get {
                return ResourceManager.GetString("Format_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        internal static string Libelle_Action_Copier_ODJ {
            get {
                return ResourceManager.GetString("Libelle_Action_Copier_ODJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        internal static string Libelle_Ajouter {
            get {
                return ResourceManager.GetString("Libelle_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un nouveau lien.
        /// </summary>
        internal static string Libelle_Ajouter_Lien {
            get {
                return ResourceManager.GetString("Libelle_Ajouter_Lien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Libelle_Annuler {
            get {
                return ResourceManager.GetString("Libelle_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a aucune actualité en ce moment..
        /// </summary>
        internal static string libelle_Aucunes_Revue_Presse {
            get {
                return ResourceManager.GetString("libelle_Aucunes_Revue_Presse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        internal static string Libelle_Boite_Recherche {
            get {
                return ResourceManager.GetString("Libelle_Boite_Recherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un lien.
        /// </summary>
        internal static string Libelle_Bouton_Ajout_Lien {
            get {
                return ResourceManager.GetString("Libelle_Bouton_Ajout_Lien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un courriel à un membre.
        /// </summary>
        internal static string Libelle_Bouton_Courriel {
            get {
                return ResourceManager.GetString("Libelle_Bouton_Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Libelle_Change_Langue {
            get {
                return ResourceManager.GetString("Libelle_Change_Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement de la liste de courriel....
        /// </summary>
        internal static string Libelle_Chargement_Courriel {
            get {
                return ResourceManager.GetString("Libelle_Chargement_Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier l&amp;#145;ordre du jour de la séance du .
        /// </summary>
        internal static string Libelle_Copier_ODJ {
            get {
                return ResourceManager.GetString("Libelle_Copier_ODJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        internal static string Libelle_deconnexion {
            get {
                return ResourceManager.GetString("Libelle_deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string Libelle_Ouvrir {
            get {
                return ResourceManager.GetString("Libelle_Ouvrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir et annoter.
        /// </summary>
        internal static string Libelle_Ouvrir_Annoter {
            get {
                return ResourceManager.GetString("Libelle_Ouvrir_Annoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le document annoté.
        /// </summary>
        internal static string Libelle_Ouvrir_Document_Annote {
            get {
                return ResourceManager.GetString("Libelle_Ouvrir_Document_Annote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochaine séance : .
        /// </summary>
        internal static string Libelle_Prochaine_Seance {
            get {
                return ResourceManager.GetString("Libelle_Prochaine_Seance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rédiger le courriel.
        /// </summary>
        internal static string Libelle_Rediger_Courriel {
            get {
                return ResourceManager.GetString("Libelle_Rediger_Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séances antérieures.
        /// </summary>
        internal static string libelle_seances_anterieures {
            get {
                return ResourceManager.GetString("libelle_seances_anterieures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger l&amp;#145;ordre du jour.
        /// </summary>
        internal static string Libelle_Telecharger_ODJ {
            get {
                return ResourceManager.GetString("Libelle_Telecharger_ODJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        internal static string Libelle_Titre {
            get {
                return ResourceManager.GetString("Libelle_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du lien.
        /// </summary>
        internal static string Libelle_Titre_Tooltip {
            get {
                return ResourceManager.GetString("Libelle_Titre_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les champs sont obligatoires..
        /// </summary>
        internal static string Libelle_Tous_Champs_Obligatoires {
            get {
                return ResourceManager.GetString("Libelle_Tous_Champs_Obligatoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes les actualités.
        /// </summary>
        internal static string libelle_Toutes_Revue_Presse {
            get {
                return ResourceManager.GetString("libelle_Toutes_Revue_Presse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Libelle_Url {
            get {
                return ResourceManager.GetString("Libelle_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL du lien.
        /// </summary>
        internal static string Libelle_Url_Tooltip {
            get {
                return ResourceManager.GetString("Libelle_Url_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions antérieures.
        /// </summary>
        internal static string Libelle_Versions_Anterieures {
            get {
                return ResourceManager.GetString("Libelle_Versions_Anterieures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet d’ordre du jour de la prochaine séance et les documents associés seront disponibles lors de l’avis de convocation  (7 jours avant la séance)..
        /// </summary>
        internal static string Message_Aucune_Seance {
            get {
                return ResourceManager.GetString("Message_Aucune_Seance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L\&apos;ordre du jour a été copié. Veuillez rafraîchir la page pour voir les points de l\&apos;ordre s\&apos;afficher..
        /// </summary>
        internal static string Message_Confirmation_Copie {
            get {
                return ResourceManager.GetString("Message_Confirmation_Copie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez remplir le champs DateSeance..
        /// </summary>
        internal static string Message_DateSeance_Obligatoire {
            get {
                return ResourceManager.GetString("Message_DateSeance_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s\&apos;est produite lors de l\&apos;éxécution de votre requête. Veuillez réessayer..
        /// </summary>
        internal static string Message_Erreur_Ajax {
            get {
                return ResourceManager.GetString("Message_Erreur_Ajax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la communication avec le serveur..
        /// </summary>
        internal static string Message_Erreur_Communication {
            get {
                return ResourceManager.GetString("Message_Erreur_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur inconnue lors de la copie de l&amp;#145;ordre du jour..
        /// </summary>
        internal static string Message_Erreur_Copie {
            get {
                return ResourceManager.GetString("Message_Erreur_Copie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le format du champ DateSeance est invalide..
        /// </summary>
        internal static string Message_Erreur_Format_Dates {
            get {
                return ResourceManager.GetString("Message_Erreur_Format_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter, SVP.
        /// </summary>
        internal static string Message_Patienter {
            get {
                return ResourceManager.GetString("Message_Patienter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez choisir une adresse..
        /// </summary>
        internal static string Message_Selection_Adresse {
            get {
                return ResourceManager.GetString("Message_Selection_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous certain de vouloir supprimer le lien?.
        /// </summary>
        internal static string Message_Supprimer_Lien {
            get {
                return ResourceManager.GetString("Message_Supprimer_Lien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceci est une page d&apos;accueil temporaire que vous devez modifier en suivant les étapes suivantes:.
        /// </summary>
        internal static string Message_Welcome_Line_1 {
            get {
                return ResourceManager.GetString("Message_Welcome_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une nouvelle page basée sur le gabarit approprié;.
        /// </summary>
        internal static string Message_Welcome_Line_2 {
            get {
                return ResourceManager.GetString("Message_Welcome_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer la page d&apos;accueil du site via cette.
        /// </summary>
        internal static string Message_Welcome_Line_3_1 {
            get {
                return ResourceManager.GetString("Message_Welcome_Line_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page de configuration.
        /// </summary>
        internal static string Message_Welcome_Line_3_2 {
            get {
                return ResourceManager.GetString("Message_Welcome_Line_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez le ou les membres à qui vous voulez envoyer un courriel.
        /// </summary>
        internal static string Note_Courriel {
            get {
                return ResourceManager.GetString("Note_Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ouvrir.
        /// </summary>
        internal static string RegExp_Bouton_Ouvrir {
            get {
                return ResourceManager.GetString("RegExp_Bouton_Ouvrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annoter.
        /// </summary>
        internal static string RegExp_Bouton_Ouvrir_Annoter {
            get {
                return ResourceManager.GetString("RegExp_Bouton_Ouvrir_Annoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annoté.
        /// </summary>
        internal static string RegExp_Bouton_Ouvrir_Document_Annote {
            get {
                return ResourceManager.GetString("RegExp_Bouton_Ouvrir_Document_Annote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environnement collaboratif sécurisé.
        /// </summary>
        internal static string Titre_Entete {
            get {
                return ResourceManager.GetString("Titre_Entete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séance du {0}.
        /// </summary>
        internal static string Titre_Page_Seance {
            get {
                return ResourceManager.GetString("Titre_Page_Seance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochaine Séance.
        /// </summary>
        internal static string Titre_Prochaine_Seance {
            get {
                return ResourceManager.GetString("Titre_Prochaine_Seance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un courriel.
        /// </summary>
        internal static string Titre_Section_Courriel {
            get {
                return ResourceManager.GetString("Titre_Section_Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liens utiles.
        /// </summary>
        internal static string Titre_Section_Liens_Utiles {
            get {
                return ResourceManager.GetString("Titre_Section_Liens_Utiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochaines Séances.
        /// </summary>
        internal static string Titre_Section_Prochaines_Seances {
            get {
                return ResourceManager.GetString("Titre_Section_Prochaines_Seances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualités.
        /// </summary>
        internal static string Titre_Section_Revue_Presse {
            get {
                return ResourceManager.GetString("Titre_Section_Revue_Presse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-ca.
        /// </summary>
        internal static string Url_Change_Langue {
            get {
                return ResourceManager.GetString("Url_Change_Langue", resourceCulture);
            }
        }
    }
}
